import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// group file, reflect the entire project
// this is where you put a reusable layout like a
// sidebar and a navigation bar
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
